### ISSUE TITLE
Creating a container fails - build fails.

### ISSUE THREAD

**Issue by tobiashochguertel** [codfish/json-server-docker#104]
Compose file:

```
services:
  api:
    image: codfish/json-server:0.17.3
    # volumes:
    # - ./my-db.js:/app/db.js:delegated
    # - ./my-middleware.js:/app/middleware.json:delegated
    # - ./my-routes.json:/app/routes.json:delegated
    volumes:
      - ./db.json:/app/db.js
      - ./public:/public
    restart: unless-stopped
```

```
❯ cd jsondummyapi
❯ ll
total 1.4M
drwxr-xr-x  3 root root 4.0K Jan 25 13:21 .
drwxr-xr-x 21 root root 4.0K Jan 25 13:19 ..
-rw-r--r--  1 root root 1.3M Jan 25 13:20 db.json
-rw-r--r--  1 root root 1.5K Jan 25 13:29 docker-compose.yml
drwxr-xr-x  3 root root 4.0K Jan 25 13:20 public

❯ start
Pulling api ... done
Creating jsondummyapi_api_1 ... done
❯ logs
Attaching to jsondummyapi_api_1
api_1  | [nodemon] 3.0.1
api_1  | [nodemon] to restart at any time, enter `rs`
api_1  | [nodemon] watching path(s): *.*
api_1  | [nodemon] watching extensions: js,mjs,ts,json,sh
api_1  | [nodemon] starting `node server.mjs`
api_1  | $ npm run build
api_1  | 
api_1  | > json-server-docker@0.0.0-semantically-released build
api_1  | > rm -rf dist && tsc
api_1  | 
rs
api_1  | db.js(2,10): error TS1005: ';' expected.
api_1  | db.js(604,13): error TS1005: ';' expected.
api_1  | db.js(4106,11): error TS1005: ';' expected.
api_1  | db.js(4608,10): error TS1005: ';' expected.
api_1  | db.js(4850,11): error TS1005: ';' expected.
api_1  | npm notice 
api_1  | npm notice New minor version of npm available! 10.1.0 -> 10.4.0
api_1  | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.4.0>
api_1  | npm notice Run `npm install -g npm@10.4.0` to update!
api_1  | npm notice 
api_1  | file:///app/node_modules/zx/build/core.js:146
api_1  |             let output = new ProcessOutput(code, signal, stdout, stderr, combined, message);
api_1  |                          ^
api_1  | 
api_1  | ProcessOutput [Error]: npm notice 
api_1  | npm notice New minor version of npm available! 10.1.0 -> 10.4.0
api_1  | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.4.0>
api_1  | npm notice Run `npm install -g npm@10.4.0` to update!
api_1  | npm notice 
api_1  |     at file:///app/server.mjs:24:8
api_1  |     exit code: 2 (Misuse of shell builtins)
api_1  |     at ChildProcess.<anonymous> (file:///app/node_modules/zx/build/core.js:146:26)
api_1  |     at ChildProcess.emit (node:events:514:28)
api_1  |     at maybeClose (node:internal/child_process:1105:16)
api_1  |     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
api_1  |     at Process.callbackTrampoline (node:internal/async_hooks:130:17) {
api_1  |   _code: 2,
api_1  |   _signal: null,
api_1  |   _stdout: '\n' +
api_1  |     '> json-server-docker@0.0.0-semantically-released build\n' +
api_1  |     '> rm -rf dist && tsc\n' +
api_1  |     '\n' +
api_1  |     "db.js(2,10): error TS1005: ';' expected.\n" +
api_1  |     "db.js(604,13): error TS1005: ';' expected.\n" +
api_1  |     "db.js(4106,11): error TS1005: ';' expected.\n" +
api_1  |     "db.js(4608,10): error TS1005: ';' expected.\n" +
api_1  |     "db.js(4850,11): error TS1005: ';' expected.\n",
api_1  |   _stderr: 'npm notice \n' +
api_1  |     'npm notice New minor version of npm available! 10.1.0 -> 10.4.0\n' +
api_1  |     'npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.4.0>\n' +
api_1  |     'npm notice Run `npm install -g npm@10.4.0` to update!\n' +
api_1  |     'npm notice \n',
api_1  |   _combined: '\n' +
api_1  |     '> json-server-docker@0.0.0-semantically-released build\n' +
api_1  |     '> rm -rf dist && tsc\n' +
api_1  |     '\n' +
api_1  |     "db.js(2,10): error TS1005: ';' expected.\n" +
api_1  |     "db.js(604,13): error TS1005: ';' expected.\n" +
api_1  |     "db.js(4106,11): error TS1005: ';' expected.\n" +
api_1  |     "db.js(4608,10): error TS1005: ';' expected.\n" +
api_1  |     "db.js(4850,11): error TS1005: ';' expected.\n" +
api_1  |     'npm notice \n' +
api_1  |     'npm notice New minor version of npm available! 10.1.0 -> 10.4.0\n' +
api_1  |     'npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.4.0>\n' +
api_1  |     'npm notice Run `npm install -g npm@10.4.0` to update!\n' +
api_1  |     'npm notice \n'
api_1  | }
api_1  | 
api_1  | Node.js v20.9.0
api_1  | [nodemon] app crashed - waiting for file changes before starting...
^CERROR: Aborting.
❯ restart
Stopping jsondummyapi_api_1 ... done
Removing jsondummyapi_api_1 ... done
Network proxy is external, skipping
Network intranet is external, skipping
Pulling api ... done
Creating jsondummyapi_api_1 ... done
Attaching to jsondummyapi_api_1
api_1  | [nodemon] 3.0.1
api_1  | [nodemon] to restart at any time, enter `rs`
api_1  | [nodemon] watching path(s): *.*
api_1  | [nodemon] watching extensions: js,mjs,ts,json,sh
api_1  | [nodemon] starting `node server.mjs`
api_1  | $ npm run build
api_1  | 
api_1  | > json-server-docker@0.0.0-semantically-released build
api_1  | > rm -rf dist && tsc
api_1  | 
api_1  | db.js(2,10): error TS1005: ';' expected.
api_1  | db.js(604,13): error TS1005: ';' expected.
api_1  | db.js(4106,11): error TS1005: ';' expected.
api_1  | db.js(4608,10): error TS1005: ';' expected.
api_1  | db.js(4850,11): error TS1005: ';' expected.
api_1  | npm notice 
api_1  | npm notice New minor version of npm available! 10.1.0 -> 10.4.0
api_1  | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.4.0>
api_1  | npm notice Run `npm install -g npm@10.4.0` to update!
api_1  | npm notice 
api_1  | file:///app/node_modules/zx/build/core.js:146
api_1  |             let output = new ProcessOutput(code, signal, stdout, stderr, combined, message);
api_1  |                          ^
api_1  | 
api_1  | ProcessOutput [Error]: npm notice 
api_1  | npm notice New minor version of npm available! 10.1.0 -> 10.4.0
api_1  | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.4.0>
api_1  | npm notice Run `npm install -g npm@10.4.0` to update!
api_1  | npm notice 
api_1  |     at file:///app/server.mjs:24:8
api_1  |     exit code: 2 (Misuse of shell builtins)
api_1  |     at ChildProcess.<anonymous> (file:///app/node_modules/zx/build/core.js:146:26)
api_1  |     at ChildProcess.emit (node:events:514:28)
api_1  |     at maybeClose (node:internal/child_process:1105:16)
api_1  |     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
api_1  |     at Process.callbackTrampoline (node:internal/async_hooks:130:17) {
api_1  |   _code: 2,
api_1  |   _signal: null,
api_1  |   _stdout: '\n' +
api_1  |     '> json-server-docker@0.0.0-semantically-released build\n' +
api_1  |     '> rm -rf dist && tsc\n' +
api_1  |     '\n' +
api_1  |     "db.js(2,10): error TS1005: ';' expected.\n" +
api_1  |     "db.js(604,13): error TS1005: ';' expected.\n" +
api_1  |     "db.js(4106,11): error TS1005: ';' expected.\n" +
api_1  |     "db.js(4608,10): error TS1005: ';' expected.\n" +
api_1  |     "db.js(4850,11): error TS1005: ';' expected.\n",
api_1  |   _stderr: 'npm notice \n' +
api_1  |     'npm notice New minor version of npm available! 10.1.0 -> 10.4.0\n' +
api_1  |     'npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.4.0>\n' +
api_1  |     'npm notice Run `npm install -g npm@10.4.0` to update!\n' +
api_1  |     'npm notice \n',
api_1  |   _combined: '\n' +
api_1  |     '> json-server-docker@0.0.0-semantically-released build\n' +
api_1  |     '> rm -rf dist && tsc\n' +
api_1  |     '\n' +
api_1  |     "db.js(2,10): error TS1005: ';' expected.\n" +
api_1  |     "db.js(604,13): error TS1005: ';' expected.\n" +
api_1  |     "db.js(4106,11): error TS1005: ';' expected.\n" +
api_1  |     "db.js(4608,10): error TS1005: ';' expected.\n" +
api_1  |     "db.js(4850,11): error TS1005: ';' expected.\n" +
api_1  |     'npm notice \n' +
api_1  |     'npm notice New minor version of npm available! 10.1.0 -> 10.4.0\n' +
api_1  |     'npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.4.0>\n' +
api_1  |     'npm notice Run `npm install -g npm@10.4.0` to update!\n' +
api_1  |     'npm notice \n'
api_1  | }
api_1  | 
api_1  | Node.js v20.9.0
api_1  | [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by frankfuu** [comment]
I ran into a similar issue, I think you need to map db.json to db.json so

instead of
```
volumes:
      - ./db.json:/app/db.js
```

try

```
volumes:
      - ./db.json:/app/db.json
```

**Comment by codfish** [comment]
Closing, as there doesn't look to be an issue with the codebase. Let me know if you have ideas on how to make the readme docs better!
